name: za_chuma
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter

    # Firebase Core
  firebase_core: ^4.1.0

    # Firebase Auth
  firebase_auth: ^6.0.2

    # Firestore for storing user info/roles
  cloud_firestore: ^6.0.1

  connectivity_plus: ^4.0.2
  sqflite: ^2.3.0
  path: ^1.8.3
  flutter_markdown: ^0.6.15
  url_launcher: ^6.1.11

    # Optional helpers
  provider: ^6.1.5      # For state management (optional)
  shared_preferences: ^2.1.0
  lucide_icons: ^0.257.0
  http: ^1.5.0
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.0
  image_picker: ^1.2.0


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/zachuma_icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^6.0.0
  flutter_launcher_icons: "^0.14.4"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/zachuma_icon.png
    - assets/images/logo-blue.png
    - assets/images/logo-orange.png
    - assets/images/bg_image1.png
    - assets/images/bg_image2.png
    - assets/images/bg_image3.png
    - assets/images/bg_image4.png
    - assets/images/bg_image5.png
    - assets/images/bg_image6.png
    - assets/images/bg_image7.png
  #   - images/a_dot_ham.jpeg

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list of fonts, each with an "asset" and other descriptors.
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope-Regular.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package