// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1SCgt_35-8wDL6fKgL4dRX_UwGjbJeeI',
    appId: '1:701115490195:web:0834a5ad6c86efc5495266',
    messagingSenderId: '701115490195',
    projectId: 'zachuma-6463f',
    authDomain: 'zachuma-6463f.firebaseapp.com',
    storageBucket: 'zachuma-6463f.firebasestorage.app',
    measurementId: 'G-4NY155KH51',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdQFurn-vkJ0ygNX2WnkSMIOhQxYZiF4k',
    appId: '1:701115490195:android:7f546acae4035961495266',
    messagingSenderId: '701115490195',
    projectId: 'zachuma-6463f',
    storageBucket: 'zachuma-6463f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNubA07vn_dylp7tcvT8QWY4SJoz8LcX8',
    appId: '1:701115490195:ios:be94c64115951897495266',
    messagingSenderId: '701115490195',
    projectId: 'zachuma-6463f',
    storageBucket: 'zachuma-6463f.firebasestorage.app',
    iosClientId: '701115490195-o1iitse5af3bmit52d25gth711gfkck2.apps.googleusercontent.com',
    iosBundleId: 'com.example.zaChuma',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNubA07vn_dylp7tcvT8QWY4SJoz8LcX8',
    appId: '1:701115490195:ios:be94c64115951897495266',
    messagingSenderId: '701115490195',
    projectId: 'zachuma-6463f',
    storageBucket: 'zachuma-6463f.firebasestorage.app',
    iosClientId: '701115490195-o1iitse5af3bmit52d25gth711gfkck2.apps.googleusercontent.com',
    iosBundleId: 'com.example.zaChuma',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1SCgt_35-8wDL6fKgL4dRX_UwGjbJeeI',
    appId: '1:701115490195:web:0095f52c1cea8690495266',
    messagingSenderId: '701115490195',
    projectId: 'zachuma-6463f',
    authDomain: 'zachuma-6463f.firebaseapp.com',
    storageBucket: 'zachuma-6463f.firebasestorage.app',
    measurementId: 'G-W3NQE0LKKE',
  );

}